{% set name = "phasorpy" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/f3/95/3913d8a8b34f3cacc41f44a6a76afca43589eb65475334539c261b4568a7/phasorpy-{{ version }}.tar.gz
  sha256: efd244d8c4cf229a79aaea80d6bc6405e5478f181aeb47b2596ad19f08f0c7c4

build:
  number: 0
  skip: true  # [py<311]
  entry_points:
    - phasorpy = phasorpy.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.1.0                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libgomp       # [linux]
  host:
    - python
    - setuptools >=68.0.0
    - numpy
    - cython >=3.1.0
    - pip
  run:
    - python
    - matplotlib-base >=3.7.0
    - scipy >=1.11.0
    - click
    - pooch
    - tqdm
    - xarray >=2023.4.0
    - tifffile >=2024.8.30
    - ptufile
    - scikit-learn >=1.5.0
    - pawflim

test:
  imports:
    - phasorpy
  commands:
    - pip check
    - phasorpy --help
  requires:
    - pip

about:
  home: https://www.phasorpy.org/
  summary: Analysis of fluorescence lifetime and hyperspectral images using the phasor approach
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://www.phasorpy.org/docs/stable/
  dev_url: https://github.com/phasorpy/phasorpy

extra:
  recipe-maintainers:
    - cgohlke
    - bruno-pannunzio
