{% set name = "phasorpy" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/phasorpy-{{ version }}.tar.gz
  sha256: 129cf46c74ea2a49ea484624e674927461ea1247ccfcd103864913c8735d22d9

build:
  number: 1
  skip: true  # [py<310]
  entry_points:
    - phasorpy = phasorpy.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.11                        # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libgomp       # [linux]
  host:
    - python
    - setuptools >=68
    - numpy
    - cython >=3.0.11
    - pip
  run:
    - python
    - matplotlib-base >=3.7.0
    - scipy >=1.11.0
    - click
    - pooch
    - tqdm
    - xarray >=2023.4.0
    - tifffile >=2024.8.30
    - ptufile

test:
  imports:
    - phasorpy
  commands:
    - pip check
    - phasorpy --help
  requires:
    - pip

about:
  home: https://www.phasorpy.org/
  summary: Analysis of fluorescence lifetime and hyperspectral images using the phasor approach
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://www.phasorpy.org/docs/stable/
  dev_url: https://github.com/phasorpy/phasorpy

extra:
  recipe-maintainers:
    - cgohlke
    - bruno-pannunzio
