{% set name = "phasorpy" %}
{% set version = "0.12" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc1cc038297ff04b55f6a3acdd676d6e73b1c53fae365c48319e2cb7044fd3ee

build:
  number: 0
  skip: true  # [py<312]
  entry_points:
    - phasorpy = phasorpy.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.2.0                         # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libgomp       # [linux]
  host:
    - python
    - vcomp14  # [win]
    - setuptools >=68.0.0
    - numpy
    - cython >=3.2.0
    - pip
  run:
    - python
    - vcomp14  # [win]
    - matplotlib-base >=3.9.0
    - scipy >=1.14.0
    - click
    - pooch
    - tqdm
    - xarray >=2024.6.0
    - tifffile >=2026.5.2
    - ptufile >=2024.9.14
    - scikit-learn >=1.5.0
    - pawflim
    - liffile >=2025.2.10
    - fbdfile >=2025.9.18
    - czifile >=2026.4.11

test:
  imports:
    - phasorpy
  commands:
    - pip check
    - phasorpy --help
  requires:
    - pip

about:
  home: https://www.phasorpy.org/
  summary: Analysis of luminescence lifetime and hyperspectral images using the phasor approach
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://www.phasorpy.org/docs/stable/
  dev_url: https://github.com/phasorpy/phasorpy

extra:
  recipe-maintainers:
    - cgohlke
    - bruno-pannunzio
